### ISSUE TITLE
Missing FTP for non premium Strava user

### ISSUE THREAD

**Issue by metyl** [mayfield/sauce#7] opened 2020-02-05 10:41 UTC
It was working before.

**Comment by mayfield** [comment] 2020-02-05 16:18
I turned off the behavior of defaulting to 200 when it was unset.  Is that what you're seeing?  You can still override the value by clicking on it.

**Comment by metyl** [comment] 2020-02-06 09:24
I'm seeing `0` which is fine if it was not set by the user but previously it shows value set by user even if the user don't have premium account, now it shows `0`.

Take my example https://www.strava.com/activities/3071940863 I had FTP set to 285 when I had premium account but now it show 0 and I'm not premium user right now. Maybe Strave removed it for ?

**Comment by mayfield** [comment] 2020-02-06 18:55
Interesting, so this is your activity which has (or had FTP) set at one point.  There was one corner case for FTP detection that I altered because I couldn't validate that it existed.  This is probably the case with your configuration.  So let me take a look at this scenario more closely.   It might be a regression.

**Comment by mayfield** [comment] 2020-02-06 19:17
Turns out I would need to setup a new account, subscribe, set the FTP then unsubscribe.   Can you do me a solid and run these two commands in the Chrome dev tools console?   I think we can narrow this down if you share the results of these two console commands.  Just go to the activity you sent me above, right click anywhere on the page and select `Inspect` then choose the `Console` tab and run each of the command below and share the results back with me.   I expect the first one might be `undefined` and if this is a regression the second one will have your FTP value displayed.

```
(new Strava.Labs.Activities.TrainingActivity({id: pageView.activity().id})).fetch({success: x => console.log(x.get('ftp'))})
```

And then

```
pageView.activity().get('ftp')
```

**Comment by metyl** [comment] 2020-02-10 09:18
Sure, I can be Your QA ;)
Seems to work - got proper value of FTP in console.

**Comment by metyl** [comment] 2020-02-12 12:10
So @mayfield will You add fix for it?

**Comment by mayfield** [comment] 2020-02-12 18:09
@metyl Already in the queue.  I implemented a change based on what I suspected was happening.  You verified that the patch will work.  It will be in the next release, thank you!!

**Closed by mayfield** 2020-02-12 18:09 UTC

**Comment by metyl** [comment] 2020-03-11 14:33
`v5.2.1` has it, thanks!
